import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeWrapper from './theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  console.log("ОБЩИЙ БЛИН ЛАЙАУУТ");
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeWrapper>
          {children}
        </ThemeWrapper>
      </body>
    </html>
  )
}
