import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeWrapper from './theme'
import Lang from './lang'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  params: any
}) {  
  return (
    <html lang="en">
      <head>
        <script src="/theme-script.js" defer></script>
      </head>
      <body className={inter.className}>
        <Lang>{children}</Lang>
      </body>
    </html>
  );
}
