// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: proto/stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetVisitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip          string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent   string `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Utm         string `protobuf:"bytes,3,opt,name=utm,proto3" json:"utm,omitempty"`
	HttpReferer string `protobuf:"bytes,4,opt,name=http_referer,json=httpReferer,proto3" json:"http_referer,omitempty"`
	Url         string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Title       string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Session     string `protobuf:"bytes,7,opt,name=session,proto3" json:"session,omitempty"`
	Unique      bool   `protobuf:"varint,8,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *SetVisitRequest) Reset() {
	*x = SetVisitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVisitRequest) ProtoMessage() {}

func (x *SetVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVisitRequest.ProtoReflect.Descriptor instead.
func (*SetVisitRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *SetVisitRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SetVisitRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SetVisitRequest) GetUtm() string {
	if x != nil {
		return x.Utm
	}
	return ""
}

func (x *SetVisitRequest) GetHttpReferer() string {
	if x != nil {
		return x.HttpReferer
	}
	return ""
}

func (x *SetVisitRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SetVisitRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SetVisitRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *SetVisitRequest) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

type VisitExtendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *VisitExtendRequest) Reset() {
	*x = VisitExtendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitExtendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitExtendRequest) ProtoMessage() {}

func (x *VisitExtendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitExtendRequest.ProtoReflect.Descriptor instead.
func (*VisitExtendRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *VisitExtendRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type SetVisitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *SetVisitResponse) Reset() {
	*x = SetVisitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVisitResponse) ProtoMessage() {}

func (x *SetVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVisitResponse.ProtoReflect.Descriptor instead.
func (*SetVisitResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *SetVisitResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type VisitExtendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *VisitExtendResponse) Reset() {
	*x = VisitExtendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_stats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitExtendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitExtendResponse) ProtoMessage() {}

func (x *VisitExtendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitExtendResponse.ProtoReflect.Descriptor instead.
func (*VisitExtendResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{3}
}

func (x *VisitExtendResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

var File_proto_stats_stats_proto protoreflect.FileDescriptor

var file_proto_stats_stats_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x22, 0xcf, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x74, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x74, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x74, 0x74,
	0x70, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x56, 0x69, 0x73, 0x69, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x2f, 0x0a, 0x13, 0x56, 0x69, 0x73, 0x69, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x32, 0x95, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x12, 0x16,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x53,
	0x65, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x46, 0x0a, 0x0b, 0x56, 0x69, 0x73, 0x69, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x12, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x45, 0x78,
	0x74, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6b, 0x31, 0x39, 0x74, 0x61, 0x2f,
	0x67, 0x6f, 0x73, 0x74, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_stats_stats_proto_rawDescOnce sync.Once
	file_proto_stats_stats_proto_rawDescData = file_proto_stats_stats_proto_rawDesc
)

func file_proto_stats_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_stats_stats_proto_rawDescData)
	})
	return file_proto_stats_stats_proto_rawDescData
}

var file_proto_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_stats_stats_proto_goTypes = []interface{}{
	(*SetVisitRequest)(nil),     // 0: stats.SetVisitRequest
	(*VisitExtendRequest)(nil),  // 1: stats.VisitExtendRequest
	(*SetVisitResponse)(nil),    // 2: stats.SetVisitResponse
	(*VisitExtendResponse)(nil), // 3: stats.VisitExtendResponse
}
var file_proto_stats_stats_proto_depIdxs = []int32{
	0, // 0: stats.StatsService.SetVisit:input_type -> stats.SetVisitRequest
	1, // 1: stats.StatsService.VisitExtend:input_type -> stats.VisitExtendRequest
	2, // 2: stats.StatsService.SetVisit:output_type -> stats.SetVisitResponse
	3, // 3: stats.StatsService.VisitExtend:output_type -> stats.VisitExtendResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stats_stats_proto_init() }
func file_proto_stats_stats_proto_init() {
	if File_proto_stats_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_stats_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVisitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stats_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitExtendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stats_stats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVisitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stats_stats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitExtendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_stats_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_stats_proto = out.File
	file_proto_stats_stats_proto_rawDesc = nil
	file_proto_stats_stats_proto_goTypes = nil
	file_proto_stats_stats_proto_depIdxs = nil
}
