// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	SetVisit(ctx context.Context, in *SetVisitRequest, opts ...grpc.CallOption) (*SetVisitResponse, error)
	VisitExtend(ctx context.Context, in *VisitExtendRequest, opts ...grpc.CallOption) (*VisitExtendResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) SetVisit(ctx context.Context, in *SetVisitRequest, opts ...grpc.CallOption) (*SetVisitResponse, error) {
	out := new(SetVisitResponse)
	err := c.cc.Invoke(ctx, "/stats.StatsService/SetVisit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) VisitExtend(ctx context.Context, in *VisitExtendRequest, opts ...grpc.CallOption) (*VisitExtendResponse, error) {
	out := new(VisitExtendResponse)
	err := c.cc.Invoke(ctx, "/stats.StatsService/VisitExtend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility
type StatsServiceServer interface {
	SetVisit(context.Context, *SetVisitRequest) (*SetVisitResponse, error)
	VisitExtend(context.Context, *VisitExtendRequest) (*VisitExtendResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatsServiceServer struct {
}

func (UnimplementedStatsServiceServer) SetVisit(context.Context, *SetVisitRequest) (*SetVisitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVisit not implemented")
}
func (UnimplementedStatsServiceServer) VisitExtend(context.Context, *VisitExtendRequest) (*VisitExtendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitExtend not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_SetVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).SetVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.StatsService/SetVisit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).SetVisit(ctx, req.(*SetVisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_VisitExtend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitExtendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).VisitExtend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.StatsService/VisitExtend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).VisitExtend(ctx, req.(*VisitExtendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetVisit",
			Handler:    _StatsService_SetVisit_Handler,
		},
		{
			MethodName: "VisitExtend",
			Handler:    _StatsService_VisitExtend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stats/stats.proto",
}
